version: '3.7'

services:
  app-name:
    image: app-name:v1
    build:
      context: .
      dockerfile: dev.Dockerfile
      # args:
      #   POSTGRES_CONNECTION_STRIG: $DATABASE_URL
    ports:
      - '3000:${SERVER_PORT}'
    depends_on:
      - redis
      - postgres
    restart: always
    environment:
      - NODE_ENV=development
    env_file:
      - .env
      - .postgresql.env

  redis:
    image: redis:7.0-rc1-alpine3.15
    restart: always
    ports:
      - 6379:${REDIS_PORT}
    command: ['redis-server', '--bind', 'redis', '--port', '6379']

  postgres:
    image: postgres:13
    restart: always
    volumes:
      - postgres-data:/data/postgres
    env_file:
      - .postgresql.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
